name: Java Docker Pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_NAMESPACE: pdrodavi
      IMAGE_TAG: ${{ github.run_number }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 and cache Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven (skip tests)
        run: mvn clean verify -DskipTests

      - name: Set APP_NAME and DOCKER_IMAGE
        run: |
          ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          echo "APP_NAME=${ARTIFACT_ID}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=${DOCKER_NAMESPACE}/${ARTIFACT_ID}" >> $GITHUB_ENV

      - name: Success message
        if: success()
        run: echo "Pipeline executado com sucesso"

      - name: Failure message
        if: failure()
        run: echo "Pipeline falhou"